SCHEMA_TYPE = '__schema_type__'
VARIADIC_TYPE = '__variadic_type__'
DEBUG = 'debug_'

MODSTACK_AUTO_TRACE_ENABLED_ENV_VAR = "MODSTACK_AUTO_TRACE_ENABLED"
MODSTACK_CONTENT_TRACING_ENABLED_ENV_VAR = "MODSTACK_CONTENT_TRACING_ENABLED"
DEFAULT_STORAGE_BATCH_SIZE = 1

GRAPH_TRIPLET_SOURCE_KEY = "triplet_source_id"
GRAPH_VECTOR_SOURCE_KEY = "vector_source_id"
GRAPH_NODES_KEY = "graph_nodes"
GRAPH_RELATIONS_KEY = "graph_relations"
GRAPH_SOURCE_REL = "SOURCE"

DATETIMETZ_FORMAT = "%Y-%m-%dT%H:%M:%S%z"