SCHEMA_TYPE = '__schema_type__'
VARIADIC_TYPE = '__variadic_type__'
DEBUG = 'debug_'

MODSTACK_AUTO_TRACE_ENABLED_ENV_VAR = "MODSTACK_AUTO_TRACE_ENABLED"
MODSTACK_CONTENT_TRACING_ENABLED_ENV_VAR = "MODSTACK_CONTENT_TRACING_ENABLED"