VARIADIC_TYPE = '__variadic_type__'
MODSTACK_ENDPOINT = '__modstack_endpoint__'
MODSTACK_RUNNABLE = '__modstack_runnable__'
IGNORE_INPUT_SCHEMA = '__ignore_input_schema__'
IGNORE_OUTPUT_SCHEMA = '__ignore_output_schema__'